### ISSUE TITLE
Starting without internet connection looses login information

### ISSUE THREAD

**Issue by sindrig** [sindrig/spoppy#134]
If you start spoppy without internet connection, it tries to login but failing because of no internet means that it discards your saved login information.

**Comment by swedishmike** [comment]
Hi there,

I'm just about to submit a pull request where the flow stops until internet connectivity is there.

This might not be exactly what you were after, and it is kind of rudimentary, but it does what it says on the tin.

Basically - if a connection can't be made to www.google.com on port 80 the program pauses for 10 seconds and tries again, until CTRL-C is pressed or a connection is established. 

Both destination and port can of course be tailored in the connectivity.py code.

// Mike

**Comment by sindrig** [comment]
Nice, thanks @swedishmike.

**Comment by sindrig** [comment]
Released in version 1.7.5
