### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by gunnardag** [sindrig/spoppy#163]
Unknown why this happens, I haven't found out any pattern when this happens.

This is printed to the console as it crashes.
```
From cffi callback <function end_of_track at 0x7f7f5e96a8c0>:
Segmentation fault (core dumped)
```

**Comment by sindrig** [comment]
@gunnardag Hopefully fixed in v2.1.4. Please re-open this ticket if this happens again, and post the last 100 lines or so from ~/.cache/spoppy/spoppy.log
